<a href="https://colab.research.google.com/github/SinghReena/MachineLearning/blob/master/Class_9_(Lists).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1 Lists**

Creating a *List*

Lists typically store homogeneous data, that is, values of the same data type. Consider the list c, which contains five integer elements:

In [ ]:
c=[-45, 6, 0, 72, 1543]
c

[-45, 6, 0, 72, 1543]

They also may store heterogeneous data, that is, data of many different types. For example, the following list contains a student’s first name (a string), last name (a string), grade point average (a float) and graduation year (an int):

In [ ]:
student=['Mary', 'Smith', 3.57, 2022]
student

['Mary', 'Smith', 3.57, 2022]

*Accessing Elements of a List*

You reference a list element by writing the list’s name followed by the element’s index (that is, its position number) enclosed in square brackets ([], known as the subscription operator). The following diagram shows the list c labeled with its element names:

![list.png]()

The first element in a list has the index 0. So, in the five-element list c, the first element is named c[0] and the last is c[4]:

In [ ]:
c[0]

-45

In [ ]:
c[4]

1543

*Determining a List’s Length*

To get a list’s length, use the built-in len function:

In [ ]:
len(c)

5

Accessing Elements from the End of the List with Negative Indices

Lists also can be accessed from the end by using negative indices:

![list1.png]()

So, list c’s last element (c[4]), can be accessed with c[-1] and its first element with c[-5]:

In [ ]:
c[-1]

1543

In [ ]:
c[-5]

-45

*Indices Must Be Integers or Integer Expressions*

An index must be an integer or integer expression

In [ ]:
a=1
b=2
c[a+b]

72

In [ ]:
c[6.7]

TypeError: ignored

Using a non-integer index value causes a TypeError.

*Lists Are Mutable*

Lists are mutable—their elements can be modified:

In [ ]:
c[4] = 17
c

[-45, 6, 0, 72, 17]

*Some Sequences Are Immutable*

Python’s string and tuple sequences are immutable—they cannot be modified. You can get the individual characters in a string, but attempting to assign a new value to one of the characters causes a TypeError:

In [ ]:
s='hello'
s[0]
s[0] = 'H'

TypeError: ignored

*Attempting to Access a Nonexistent Element*

Using an out-of-range list, tuple or string index causes an IndexError:

In [ ]:
c[100]

IndexError: ignored

*Using List Elements in Expressions*

List elements may be used as variables in expressions:

In [ ]:
c[0]+c[1]+c[2]

-39

*Appending to a List with +=*

Let’s start with an empty list [], then use a for statement and += to append the values 1 through 5 to the list—the list grows dynamically to accommodate each item:

In [ ]:
a_list = []
for number in range(1,6):
  a_list += [number]

a_list

[1, 2, 3, 4, 5]

When the left operand of += is a list, the right operand must be an iterable; otherwise, a TypeError occurs. The square brackets around number create a one-element list, which we append to a_list. If the right operand contains multiple elements, += appends them all.


The following appends the characters of 'Python' to the list letters:

In [ ]:
letters = []
letters += "Python"

letters

['P', 'y', 't', 'h', 'o', 'n']

If the right operand of += is a tuple, its elements also are appended to the list.

*Concatenating Lists with +*

You can concatenate two lists, two tuples or two strings using the + operator. The result is a new sequence of the same type containing the left operand’s elements followed by the right operand’s elements. The original sequences are unchanged:

In [ ]:
list1 = [10,20,30]

list2 = [40, 50]

concatenated_list = list1 + list2

concatenated_list

[10, 20, 30, 40, 50]

A TypeError occurs if the + operator’s operands are difference sequence types—for example, concatenating a list and a tuple is an error.

*Using for and range to Access List Indices and Values*

List elements also can be accessed via their indices and the subscription operator ([]):

In [ ]:
for i in range(len(concatenated_list)): 
  print(f'{i}: {concatenated_list[i]}')

0: 10
1: 20
2: 30
3: 40
4: 50

The function call range(len(concatenated_list)) produces a sequence of integers representing concatenated_list’s indices (in this case, 0 through 4). When looping in this manner, you must ensure that indices remain in range.

*Comparison Operators*

You can compare entire lists element-by-element using comparison operators:

In [ ]:
a = [1,2,3]

b = [5,6,7]

c= [ 1,2, 3, 4]

print(a == b)
print(a == c)
print(a < c)
print(c >= b)

False
False
True
False

**1.2 Sequence Slicing**

You can slice sequences to create new sequences of the same type containing subsets of the original elements. Slice operations can modify mutable sequences—those that do not modify a sequence work identically for lists, tuples and strings.

*Specifying a Slice with Starting and Ending Indices*

Let’s create a slice consisting of the elements at indices 2 through 5 of a list:

In [ ]:
numbers = [2, 3, 5, 7, 11, 13, 17, 19]
numbers[2:6]

[5, 7, 11, 13]

The slice copies elements from the starting index to the left of the colon (2) up to, but not including, the ending index to the right of the colon (6). The original list is not modified.

*Specifying a Slice with Only an Ending Index*

If you omit the starting index, 0 is assumed. So, the slice numbers[:6] is equivalent to the slice numbers[0:6]:

In [ ]:
numbers[:6]

[2, 3, 5, 7, 11, 13]

In [ ]:
numbers[0:6]

[2, 3, 5, 7, 11, 13]

*Specifying a Slice with Only a Starting Index*

If you omit the ending index, Python assumes the sequence’s length (8 here), so slice contains the elements of numbers at indices 6 and 7:

In [ ]:
numbers[6:]

[17, 19]

In [ ]:
numbers[6:len(numbers)]

[17, 19]

*Specifying a Slice with No Indices*

Omitting both the start and end indices copies the entire sequence:

In [ ]:
numbers[:]

[2, 3, 5, 7, 11, 13, 17, 19]

Though slices create new objects, slices make shallow copies of the elements—that is, they copy the elements’ references but not the objects they point to. So, in the snippet above, the new list’s elements refer to the same objects as the original list’s elements, rather than to separate copies.

*Slicing with Steps*

The following code uses a step of 2 to create a slice with every other element of numbers:

In [ ]:
numbers[::2]

['two', 'five']

We omitted the start and end indices, so 0 and len(numbers) are assumed, respectively.

*Slicing with Negative Indices and Steps*

You can use a negative step to select slices in reverse order. The following code concisely creates a new list in reverse order:

In [ ]:
numbers[::-1]

['five', 'three', 'two']

This is equivalent to:

In [ ]:
numbers[-1:-9:-1]

['five', 'three', 'two']

*Modifying Lists Via Slices*

You can modify a list by assigning to a slice of it—the rest of the list is unchanged. The following code replaces numbers’ first three elements, leaving the rest unchanged:

In [ ]:
numbers[0:3] = ['two', 'three', 'five']

numbers

['two', 'three', 'five', 19]

The following deletes only the first three elements of numbers by assigning an empty list to the three-element slice:

In [ ]:
numbers[0:4] = []

numbers

[100, 13, 100, 19]

The following assigns a list’s elements to a slice of every other element of numbers:

In [ ]:
numbers = [2, 3, 5, 7, 11, 13, 17, 19]

numbers[::2] = [100, 100, 100, 100]


print(numbers)

id(numbers)

[100, 3, 100, 7, 100, 13, 100, 19]

139697844197568

Let’s delete all the elements in numbers, leaving the existing list empty:

In [ ]:
numbers[:] = []

print(numbers)

id(numbers)

[]

139697844197568

Deleting numbers’ contents  is different from assigning numbers a new empty list [] . To prove this, we display numbers’ identity after each operation. The identities are different, so they represent separate objects in memory:

In [ ]:
numbers = []

print(numbers)

id(numbers)

[]

139697768644512

**1.3 del Statement**

The del statement also can be used to remove elements from a list and to delete variables from the interactive session. You can remove the element at any valid index or the element(s) from any valid slice.

*Deleting the Element at a Specific List Index*

Let’s create a list, then use del to remove its last element:

In [ ]:
numbers = list(range(0, 10))
print(numbers)
del numbers[-1]
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]

*Deleting a Slice from a List*

The following deletes the list’s first two elements:

In [ ]:
del numbers[0:2]
print(numbers)

[2, 3, 4, 5, 6, 7, 8]

The following uses a step in the slice to delete every other element from the entire list:

In [ ]:
del numbers[::2]
print(numbers)

[3, 5, 7]

*Deleting a Slice Representing the Entire List*

The following code deletes all of the list’s elements:

In [ ]:
del numbers[:]
print(numbers)

[]

*Deleting a Variable from the Current Session*

The del statement can delete any variable. Let’s delete numbers from the interactive session, then attempt to display the variable’s value, causing a NameError:

In [ ]:
del numbers
print(numbers)

NameError: ignored

1.4 Passing Lists to Functions

All objects are passed by reference and demonstrated passing an immutable object as a function argument. Here, we discuss references further by examining what happens when a program passes a mutable list object to a function.

*Passing an Entire List to a Function*

Consider the function modify_elements, which receives a reference to a list and multiplies each of the list’s element values by 2:

In [ ]:
def modify_elements(items):
  """"Multiplies all element values in items by 2."""
  for i in range(len(items)):
    items[i] *= 2

numbers = [10, 3, 7, 1, 9]

modify_elements(numbers)

print(numbers)

[20, 6, 14, 2, 18]

Function modify_elements’ items parameter receives a reference to the original list, so the statement in the loop’s suite modifies each element in the original list object.

*Passing a Tuple to a Function*

When you pass a tuple to a function, attempting to modify the tuple’s immutable elements results in a TypeError:

In [ ]:
numbers_tuple = (10, 20, 30)
print(numbers_tuple)

modify_elements(numbers_tuple)

(10, 20, 30)

TypeError: ignored

Recall that tuples may contain mutable objects, such as lists. Those objects still can be modified when a tuple is passed to a function.

**1.5  Sorting Lists**

Sorting enables you to arrange data either in ascending or descending order.

*Sorting a List in Ascending Order*

List method sort modifies a list to arrange its elements in ascending order:

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6,"Reena"]
numbers.sort()
print(numbers)

TypeError: ignored

*Sorting a List in Descending Order*

To sort a list in descending order, call list method sort with the optional keyword argument reverse set to True (False is the default):

In [ ]:
numbers.sort(reverse=True)
print(numbers)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

*Built-In Function sorted*

Built-in function sorted returns a new list containing the sorted elements of its argument sequence—the original sequence is unmodified. The following code demonstrates function sorted for a list, a string and a tuple:

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
ascending_numbers = sorted(numbers)
print(ascending_numbers)
print(numbers)

letters = 'fadgchjebi'
ascending_letters = sorted(letters)
print(ascending_letters)

print(letters)

colors = ('red', 'orange', 'yellow', 'green', 'blue')

ascending_colors = sorted(colors)

print(ascending_colors)

print(colors)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
fadgchjebi
['blue', 'green', 'orange', 'red', 'yellow']
('red', 'orange', 'yellow', 'green', 'blue')

Use the optional keyword argument reverse with the value True to sort the elements in descending order.

**1.6 Searching Sequences**

Searching is the process of locating a key.

*List Method index*

List method index takes as an argument a search key—the value to locate in the list—then searches through the list from index 0 and returns the index of the first element that matches the search key:

In [ ]:
numbers = [3, 7, 1, 4, 2, 8, 5, 6]
numbers.index(10)

ValueError: ignored

A ValueError occurs if the value you’re searching for is not in the list.

*Specifying the Starting Index of a Search*

Using method index’s optional arguments, you can search a subset of a list’s elements. You can use *= to multiply a sequence—that is, append a sequence to itself multiple times. After the following snippet, numbers contains two copies of the original list’s contents:

In [ ]:
numbers *= 2
print(numbers)

[3, 7, 1, 4, 2, 8, 5, 6, 3, 7, 1, 4, 2, 8, 5, 6]

The following code searches the updated list for the value 5 starting from index 7 and continuing through the end of the list:

In [ ]:
numbers.index(5, 7)

14

*Specifying the Starting and Ending Indices of a Search*

Specifying the starting and ending indices causes index to search from the starting index up to but not including the ending index location. 

numbers.index(5, 7)

assumes the length of numbers as its optional third argument and is equivalent to:

numbers.index(5, 7, len(numbers))

The following looks for the value 7 in the range of elements with indices 0 through 3:

In [ ]:
numbers.index(7, 0, 4)

1

*Operators in and not in*

Operator in tests whether its right operand’s iterable contains the left operand’s value:

In [ ]:
1000 in numbers

False

In [ ]:
5 in numbers

True

Similarly, operator not in tests whether its right operand’s iterable does not contain the left operand’s value:

In [ ]:
1000 not in numbers

True

In [ ]:
5 not in numbers

False

*Using Operator in to Prevent a ValueError*

You can use the operator in to ensure that calls to method index do not result in ValueErrors for search keys that are not in the corresponding sequence:

In [ ]:
search_key = 5
if key in numbers:
  print(f'found {key} at index {numbers.index(search_key)}')
else:
  print(f'{key} not found')

found 5 at index 6

*Built-In Functions any and all*

Sometimes you simply need to know whether any item in an iterable is True or whether all the items are True. The built-in function any returns True if any item in its iterable argument is True. The built-in function all returns True if all items in its iterable argument are True. Recall that nonzero values are True and 0 is False. Non-empty iterable objects also evaluate to True, whereas any empty iterable evaluates to False. Functions any and all are additional examples of internal iteration in functional-style programming.

**1.7 Other List Methods**

Lists also have methods that add and remove elements. Consider the list color_names:

In [ ]:
color_names = ['orange', 'yellow', 'green']

*Inserting an Element at a Specific List Index*

Method insert adds a new item at a specified index. The following inserts 'red' at index 0:

In [ ]:
color_names.insert(0, 'red')
print(color_names)

['red', 'orange', 'yellow', 'green']

*Adding an Element to the End of a List*

You can add a new item to the end of a list with method append:

In [ ]:
color_names.append('blue')
print(color_names)

['red', 'orange', 'yellow', 'green', 'blue']

*Adding All the Elements of a Sequence to the End of a List*

Use list method extend to add all the elements of another sequence to the end of a list:

In [ ]:
color_names.extend(['indigo', 'violet'])
print(color_names)

['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']

This is the equivalent of using +=. The following code adds all the characters of a string then all the elements of a tuple to a list:

In [ ]:
sample_list = []
s = 'abc'
sample_list.extend(s)
print(sample_list)
t = (1, 2, 3)
sample_list.extend(t)
print(sample_list)

['a', 'b', 'c']
['a', 'b', 'c', 1, 2, 3]

Rather than creating a temporary variable, like t, to store a tuple before appending it to a list, you might want to pass a tuple directly to extend. In this case, the tuple’s parentheses are required, because extend expects one iterable argument:

In [ ]:
sample_list.extend((4, 5, 6)) # note the extra parentheses
print(sample_list)

['a', 'b', 'c', 1, 2, 3, 4, 5, 6]

A TypeError occurs if you omit the required parentheses.

*Removing the First Occurrence of an Element in a List*

Method remove deletes the first element with a specified value—a ValueError occurs if remove’s argument is not in the list:

In [ ]:
color_names.remove('green')
print(color_names)

['red', 'orange', 'yellow', 'blue', 'indigo', 'violet']

*Emptying a List*

To delete all the elements in a list, call method clear:

In [ ]:
color_names.clear()
print(color_names)

This is the equivalent of the previously shown slice assignment

In [ ]:
color_names[:] = []

*Counting the Number of Occurrences of an Item*

List method count searches for its argument and returns the number of times it is found:

In [ ]:
responses = [1, 2, 5, 4, 3, 5, 2, 1, 3, 3,1, 4, 3, 3, 3, 2, 3, 3, 2, 2]
for i in range(1, 6):
  print(f'{i} appears {responses.count(i)} times in responses')

1 appears 3 times in responses
2 appears 5 times in responses
3 appears 8 times in responses
4 appears 2 times in responses
5 appears 2 times in responses

*Reversing a List’s Elements*

List method reverse reverses the contents of a list in place, rather than creating a reversed copy

In [ ]:
color_names = ['red', 'orange', 'yellow', 'green', 'blue']
color_names.reverse()
print(color_names)

['blue', 'green', 'yellow', 'orange', 'red']

*Copying a List*

List method copy returns a new list containing a shallow copy of the original list:

In [ ]:
copied_list = color_names.copy()
print(copied_list)

['blue', 'green', 'yellow', 'orange', 'red']

This is equivalent to the previously demonstrated slice operation:

In [ ]:
copied_list = color_names[:]

**1.8 List Comprehensions**

List comprehensions can replace many for statements that iterate over existing sequences and create new lists, such as:

In [ ]:
list1 = []
for item in range(1, 6):
  list1.append(item)
print(list1)

[1, 2, 3, 4, 5]

*Using a List Comprehension to Create a List of Integers*

We can accomplish the same task in a single line of code with a list comprehension:

In [ ]:
list2 = [item for item in range(1, 6)]
print(list2)

[1, 2, 3, 4, 5]

for statement, the list comprehension’s for clause for item in range(1, 6) iterates over the sequence produced by range(1, 6). For each item, the list comprehension evaluates the expression to the left of the for clause and places the expression’s value (in this case, the item itself) in the new list.

Comprehension could have been expressed more concisely using the function list:

In [ ]:
list2 = list(range(1, 6))
print(list2)

*Mapping: Performing Operations in a List Comprehension’s Expression*

A list comprehension’s expression can perform tasks, such as calculations, that map elements to new values (possibly of different types). Mapping is a common functional-style programming operation that produces a result with the same number of elements as the original data being mapped. The following comprehension maps each value to its cube with the expression item ** 3:

In [ ]:
list3 = [item ** 3 for item in range(1, 6)]
print(list3)

[1, 8, 27, 64, 125]

*Filtering: List Comprehensions with if Clauses*

Another common functional-style programming operation is filtering elements to select only those that match a condition. This typically produces a list with fewer elements than the data being filtered. To do this in a list comprehension, use the if clause. The following includes in list4 only the even values produced by the for clause:

In [ ]:
list4 = [item for item in range(1, 11) if item % 2 == 0]
print(list4)

[2, 4, 6, 8, 10]

*List Comprehension That Processes Another List’s Elements*

The for clause can process any iterable. Let’s create a list of lowercase strings and use a list comprehension to create a new list containing their uppercase versions:

In [ ]:
colors = ['red', 'orange', 'yellow', 'green', 'blue']
colors2 = [item.upper() for item in colors]
print(colors2)
print(colors)

['RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE']
['red', 'orange', 'yellow', 'green', 'blue']

**1.9 Filter, Map and Reduce**

*Filtering a Sequence’s Values with the Built-In filter Function*

Let’s use built-in function filter to obtain the odd values in numbers:

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
def is_odd(x):
  """Returns True only if x is odd."""
  return x % 2 != 0
list(filter(is_odd, numbers))

[3, 7, 1, 9, 5]

Like data, Python functions are objects that you can assign to variables, pass to other functions and return from functions. Functions that receive other functions as arguments are a functional-style capability called higher-order functions. For example, filter’s first argument must be a function that receives one argument and returns True if the value should be included in the result. The function is_odd returns True if its argument is odd. The filter function calls is_odd once for each value in its second argument’s iterable (numbers). Higher-order functions may also return a function as a result. 


Function filter returns an iterator, so filter’s results are not produced until you iterate through them. This is another example of lazy evaluation. Function list iterates through the results and creates a list containing them. We can obtain the same results as above by using a list comprehension with an if clause:

In [ ]:
[item for item in numbers if is_odd(item)]

[3, 7, 1, 9, 5]

*Using a lambda Rather than a Function*

For simple functions like is_odd that return only a single expression’s value, you can use a lambda expression (or simply a lambda) to define the function inline where it’s needed—typically as it’s passed to another function:

In [ ]:
list(filter(lambda x: x % 2 != 0, numbers))

[3, 7, 1, 9, 5]

We pass filter’s return value (an iterator) to function list here to convert the results to a list and display them.

A lambda expression is an anonymous function—that is, a function without a name. In the filter call

filter(lambda x: x % 2 != 0, numbers)

the first argument is the lambda

lambda x: x % 2 != 0

A lambda begins with the lambda keyword followed by a comma-separated parameter list, a colon (:) and an expression. In this case, the parameter list has one parameter named x. A lambda implicitly returns its expression’s value. So any simple function of the form


def function_name(parameter_list): 
  return expression


may be expressed as a more concise lambda of the form
lambda parameter_list: expression

*Mapping a Sequence’s Values to New Values*

Let’s use built-in function map with a lambda to square each value in numbers:

In [ ]:
numbers
print(numbers)

list(map(lambda x: x ** 2, numbers))

[10, 3, 7, 1, 9, 4, 2, 8, 5, 6]

[100, 9, 49, 1, 81, 16, 4, 64, 25, 36]

Function map’s first argument is a function that receives one value and returns a new value—in this case, a lambda that squares its argument. The second argument is an iterable of values to map. Function map uses lazy evaluation. So, we pass to the list function the iterator that map returns. This enables us to iterate through and create a list of the mapped values. Here’s an equivalent list comprehension:

In [ ]:
[item ** 2 for item in numbers]

[100, 9, 49, 1, 81, 16, 4, 64, 25, 36]

*Combining filter and map*

You can combine the preceding filter and map operations as follows:

In [ ]:
list(map(lambda x: x ** 2,filter(lambda x: x % 2 != 0, numbers)))

[9, 49, 1, 81, 25]

First, filter returns an iterable representing only the odd values of numbers. Then map returns an iterable representing the squares of the filtered values. Finally, list uses map’s iterable to create the list. You might prefer the following list comprehension to the preceding snippet:

In [ ]:
[x ** 2 for x in numbers if x % 2 != 0]

[9, 49, 1, 81, 25]

For each value of x in numbers, the expression x ** 2 is performed only if the condition x % 2 != 0 is True.

**1.10 Other Sequence Processing Functions**

Python provides other built-in functions for manipulating sequences.

*Finding the Minimum and Maximum Values Using a Key Function*

The built-in reduction functions min and max using arguments, such as ints or lists of ints. Sometimes you’ll need to find the minimum and maximum of more complex objects, such as strings. Consider the following comparison:

In [ ]:
'Red' < 'orange'

True

The letter 'R' “comes after” 'o' in the alphabet, so you might expect 'Red' to be less than 'orange' and the condition above to be False. However, strings are compared by their characters’ underlying numerical values, and lowercase letters have higher numerical values than uppercase letters. You can confirm this with built-in function ord, which returns the numerical value of a character:

In [ ]:
ord('R')

82

In [ ]:
ord('o')

111

Consider the list colors, which contains strings with uppercase and lowercase letters:

In [ ]:
colors = ['Red', 'orange', 'Yellow', 'green', 'Blue']

Let’s assume that we’d like to determine the minimum and maximum strings using alphabetical order, not numerical (lexicographical) order. If we arrange colors alphabetically

'Blue', 'green', 'orange', 'Red', 'Yellow'

'Blue' is the minimum (that is, closest to the beginning of the alphabet), and 'Yellow' is the maximum (that is, closest to the end of the alphabet).

Since Python compares strings using numerical values, you must first convert each string to all lowercase or all uppercase letters. Then their numerical values will also represent alphabetical ordering. The following snippets enable min and max to determine the minimum and maximum strings alphabetically:

In [ ]:
min(colors, key=lambda s: s.lower())

'blue'

In [ ]:
max(colors, key=lambda s: s.lower())

'yellow'

The key keyword argument must be a one-parameter function that returns a value. In this case, it’s a lambda that calls string method lower to get a string’s lowercase version. Functions min and max call the key argument’s function for each element and use the results to compare the elements.

*Iterating Backward Through a Sequence*

Built-in function reversed returns an iterator that enables you to iterate over a sequence’s values backward. The following list comprehension creates a new list containing the squares of numbers’ values in reverse order:

In [ ]:
numbers = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]

reversed_numbers = [item for item in reversed(numbers)]

reversed_numbers

[6, 5, 8, 2, 4, 9, 1, 7, 3, 10]

*Combining Iterables into Tuples of Corresponding Elements*

Built-in function zip enables you to iterate over multiple iterables of data at the same time. The function receives as arguments any number of iterables and returns an iterator that produces tuples containing the elements at the same index in each. For example,zip produces the tuples ('Bob', 3.5), ('Sue', 4.0) and ('Amanda', 3.75) consisting of the elements at index 0, 1 and 2 of each list, respectively:

In [ ]:
names = ['Bob', 'Sue', 'Amanda']
grade_point_averages = [3.5, 4.0, 3.75]
for name, gpa in zip(names, grade_point_averages):
  print(f'Name={name}; GPA={gpa}')

Name=Bob; GPA=3.5
Name=Sue; GPA=4.0
Name=Amanda; GPA=3.75

Unpack each tuple into name and gpa and display them. Function zip’s shortest argument determines the number of tuples produced. Here both have the same length.

**1.11 Two-Dimensional Lists**

Lists can contain other lists as elements. A typical use of such nested (or multidimensional) lists is to represent tables of values consisting of information arranged in rows and columns. To identify a particular table element, we specify two indices—by convention, the first identifies the element’s row, the second the element’s column.

Lists that require two indices to identify an element are called two-dimensional lists (or double-indexed lists or double-subscripted lists ). Multidimensional lists can have more than two indices. Here, we introduce two-dimensional lists.

*Creating a Two-Dimensional List*

Consider a two-dimensional list with three rows and four columns (i.e., a 3-by-4 list) that might represent the grades of three students who each took four exams in a course:

In [ ]:
a = [[77, 68, 86, 73], [96, 87, 89, 81], [70, 90, 86, 81]]

Writing the list as follows makes its row and column tabular structure clearer:

In [ ]:
a = [[77, 68, 86, 73], # first student's grades 
     [96, 87, 89, 81], # second student's grades 
     [70, 90, 86, 81]] # third student's grades

*Illustrating a Two-Dimensional List*

The diagram below shows the list a, with its rows and columns of exam grade values:

![rowcol.png]()

*Identifying the Elements in a Two-Dimensional List*

The following diagram shows the names of list a’s elements:

![rowcol1.png]()

Every element is identified by a name of the form a[ i ][ j ]—a is the list’s name, and i and j are the indices that uniquely identify each element’s row and column, respectively. The element names in row 0 all have 0 as the first index. The element names in column 3 all have 3 as the second index.

In the two-dimensional list a:

77, 68, 86 and 73 initialize a[0][0], a[0][1], a[0][2] and a[0][3], respectively,

96, 87, 89 and 81 initialize a[1][0], a[1][1], a[1][2] and a[1][3], respectively, and

70, 90, 86 and 81 initialize a[2][0], a[2][1], a[2][2] and a[2][3], respectively.

A list with m rows and n columns is called an m-by-n list and has m × n elements.

The following nested for statement outputs the rows of the preceding two-dimensional list one row at a time:

In [ ]:
for row in a:
  for item in row:
    print(item, end=' ')
  print()

77 68 86 73
96 87 89 81
70 90 86 81

*How the Nested Loops Execute*

Let’s modify the nested loop to display the list’s name and the row and column indices and value of each element:

In [ ]:
for i, row in enumerate(a):
  for j, item in enumerate(row):
    print(f'a[{i}][{j}]={item} ', end=' ')
  print()

a[0][0]=77  a[0][1]=68  a[0][2]=86  a[0][3]=73
a[1][0]=96  a[1][1]=87  a[1][2]=89  a[1][3]=81
a[2][0]=70  a[2][1]=90  a[2][2]=86  a[2][3]=81

The outer for statement iterates over the two-dimensional list’s rows one row at a time. During each iteration of the outer for statement, the inner for statement iterates over each column in the current row. So in the first iteration of the outer loop, row 0 is

[77, 68, 86, 73]

and the nested loop iterates through this list’s four elements a[0][0]=77, a[0][1]=68, a[0][2]=86 and a[0][3]=73.

In the second iteration of the outer loop, row 1 is

[96, 87, 89, 81]

and the nested loop iterates through this list’s four elements a[1][0]=96, a[1][1]=87, a[1][2]=89 and a[1][3]=81.

In the third iteration of the outer loop, row 2 is

[70, 90, 86, 81]

and the nested loop iterates through this list’s four elements a[2][0]=70, a[2][1]=90, a[2][2]=86 and a[2][3]=81.